import {WindupExecution} from "windup-services";

export const EXECUTIONS_DATA: WindupExecution[] = [
    {
        "id": 13,
        "version": 1,
        "timeStarted": 1477907641905,
        "timeCompleted": 1477907647229,
        "outputPath": "/home/dklingen/apps/wildfly-10.1.0.Final/standalone/data/windup/reports/Default Group.ANnIuZsNxbfq.report",
        "totalWork": 0,
        "workCompleted": 0,
        "currentTask": null,
        "lastModified": 1477907647318,
        "state": "COMPLETED",
        "analysisContext": null,
        "filterApplications": null,
        "outputDirectoryName": "Default Group.ANnIuZsNxbfq.report",
        "applicationListRelativePath": "Default Group.ANnIuZsNxbfq.report/index.html"
    },
    {
        "id": 15,
        "version": 1,
        "timeStarted": 1477907945127,
        "timeCompleted": 1477907948439,
        "outputPath": "/home/dklingen/apps/wildfly-10.1.0.Final/standalone/data/windup/reports/Default Group.ANnIuZsNxbfq.report",
        "totalWork": 0,
        "workCompleted": 0,
        "currentTask": null,
        "lastModified": 1477907948484,
        "state": "FAILED",
        "analysisContext": null,
        "filterApplications": null,
        "outputDirectoryName": "Default Group.ANnIuZsNxbfq.report",
        "applicationListRelativePath": "Default Group.ANnIuZsNxbfq.report/index.html"
    },
    {
        "id": 25,
        "version": 27,
        "timeStarted": 1478000242721,
        "timeCompleted": null,
        "outputPath": "/home/dklingen/apps/wildfly-10.1.0.Final/standalone/data/windup/reports/Default Group.ANnIuZsNxbfq.report",
        "totalWork": 757,
        "workCompleted": 5,
        "currentTask": "PostFinalizePhase - RenderRuleProviderReportRuleProvider - RenderRuleProviderReportRuleProvider_1",
        "lastModified": 1478000316581,
        "state": "STARTED",
        "analysisContext": null,
        "filterApplications": null,
        "outputDirectoryName": "Default Group.ANnIuZsNxbfq.report",
        "applicationListRelativePath": "Default Group.ANnIuZsNxbfq.report/index.html"
    },
    {
        "id": 30,
        "version": 30,
        "timeStarted": null,
        "timeCompleted": null,
        "outputPath": null,
        "totalWork": 757,
        "workCompleted": 0,
        "currentTask": null,
        "lastModified": 1478000242721,
        "state": "QUEUED",
        "analysisContext": null,
        "filterApplications": null,
        "outputDirectoryName": "Default Group.ANnIuZsNxbfq.report",
        "applicationListRelativePath": "Default Group.ANnIuZsNxbfq.report/index.html"
    },
    {
        "id": 35,
        "version": 35,
        "timeStarted": 1478000242721,
        "timeCompleted": null,
        "outputPath": null,
        "totalWork": 757,
        "workCompleted": 0,
        "currentTask": null,
        "lastModified": 1478000242721,
        "state": "CANCELLED",
        "analysisContext": null,
        "filterApplications": null,
        "outputDirectoryName": "Default Group.ANnIuZsNxbfq.report",
        "applicationListRelativePath": "Default Group.ANnIuZsNxbfq.report/index.html"
    },
];
