name: Windup web PR builder for JDK11

on:
  pull_request:
    branches:
      - master
      - 'releases/**'

jobs:

  windup-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          repository: windup/windup
          ref: ${{ github.base_ref }}
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          java-package: jdk
      - name: Cache local Maven repository
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-windup-build-${{ github.sha }}
      - name: Build Windup on JDK 11
        run: mvn -B clean install -DskipTests

  windup-rulesets-build:
    runs-on: ubuntu-latest
    needs: [windup-build]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          repository: windup/windup-rulesets
          ref: ${{ github.base_ref }}
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          java-package: jdk
      - name: Cache local Maven repository
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-windup-rulesets-build-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-maven-windup-build-${{ github.sha }}
      - name: Build Windup Rulesets
        run: mvn -B clean install -DskipTests

  windup-cli-build:
    runs-on: ubuntu-latest
    needs: [windup-rulesets-build]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          repository: windup/windup-distribution
          ref: ${{ github.base_ref }}
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          java-package: jdk
      - name: Cache local Maven repository
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-windup-cli-build-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-maven-windup-rulesets-build-${{ github.sha }}
      - name: Build on JDK 11
        run: mvn -B clean install -DskipTests

  windup-web-build:
    runs-on: ubuntu-latest
    needs: [windup-cli-build]
    env:
      OPENSSL_CONF: /etc/ssl
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          java-package: jdk
      - name: Cache local Maven repository
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-windup-web-build-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-maven-windup-cli-build-${{ github.sha }}
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
      - name: Build
        run: mvn clean install -U -s settings.xml
